#!/bin/bash

set -ex
. ./functions

V=2
if [ -f /sys/module/ploop/parameters/large_disk_support ]; then
	SIZENEW=60485760000
else
	SIZENEW=2147482624
fi

while [ "${#}" -gt 0 ]; do
case "${1}" in
	"-v")
		V=${2}
		shift
		shift
		;;
	*)
		shift
		;;
	esac
done

test_cleanup

ploop init -s 10G $TEST_IMAGE >>$TEST_LOG 2>&1
dd if=/dev/zero of=$TEST_STORAGE/data bs=4K count=100 >>$TEST_LOG 2>&1
dd if=/dev/urandom of=$TEST_STORAGE/data bs=4K count=100 seek=100 >>$TEST_LOG 2>&1
ploop mount -d /dev/ploop0 -m $TEST_MNT $TEST_DDXML >>$TEST_LOG 2>&1
for ((i=0; i<1000; i++)); do
	dd if=$TEST_STORAGE/data of=$TEST_MNT/$i bs=1k >>$TEST_LOG 2>&1
done
ploop snapshot  $TEST_DDXML >>$TEST_LOG 2>&1
ploop umount -d /dev/ploop0 -m $TEST_MNT $TEST_DDXML >>$TEST_LOG 2>&1
tar --sparse -C / -cvf $TEST_STORAGE/data.tar ${TEST_IMAGE}* 
rm -f ${TEST_IMAGE}*
tar --sparse -C / -xvf $TEST_STORAGE/data.tar
exit
ploop mount -d /dev/ploop0 -m $TEST_MNT $TEST_DDXML >>$TEST_LOG 2>&1
M1=`md5sum $TEST_STORAGE/data`
for ((i=0 i<5000; i++)); do
	M1_1=`md5sum $TEST_MNT/$i`
	if [ "$M1" != "$M1_1" ]; then
		echo "FAILED md5 mismatch $M1 != $M1_1"
		exit 1
	fi
done
ploop umount $TEST_DDXML >>$TEST_LOG 2>&1
test_cleanup
echo "FINISHED [OK]"
